Fix warning for incompatible function cast
With pedatnic option (strict warnings) ans MINGW64,
the GetProcAddress() cannot be simple casted, as it leads to
 error: cast between incompatible function types from 'FARPROC' ...

Introduce local macro that will wrap all such calls
and silences benign warnings.