Fix ignoring return value in RCU witn MINGW 32bit
For code that uses NO_INTERLOCKEDOR64 (Win32 32bit),
there is a warning in RCU code
    error: ignoring return value of 'CRYPTO_THREAD_write_lock'
    declared with attribute 'warn_unused_result' [-Werror=unused-result]

As the function cannot fail on that platform (and error
path would need some reverts leading to impossible dereference later),
just use trick to silence the warning.